### ISSUE TITLE
update osmosis asset list to latest

### ISSUE THREAD

**Issue by aidanaden** [cosmology-tech/cosmology#12]
The current asset list used [https://github.com/cosmology-tech/cosmology/blob/main/packages/core/src/assets/assetlist.json](https://github.com/cosmology-tech/cosmology/blob/main/packages/core/src/assets/assetlist.json) is out-of-date, the asset list by osmosis-labs [https://github.com/osmosis-labs/assetlists/blob/main/osmosis-1/osmosis-1.assetlist.json](https://github.com/osmosis-labs/assetlists/blob/main/osmosis-1/osmosis-1.assetlist.json) has recently been updated with a few new assets including kujira

**Comment by pyramation** [comment]
thanks @aidanaden — checkout latest!
