### ISSUE TITLE
bug: `makePoolsPretty` is not a function in production build

### ISSUE THREAD

**Issue by aidanaden** [cosmology-tech/cosmology#16]
![image](https://user-images.githubusercontent.com/26812563/193953692-ff9a1133-7153-492e-b597-b6078eb4626b.png)

Hi! am currently receiving this error message in production build, but i'm still not sure what the issue is, everything works fine locally.

Node version used is `14.19.2`, built with vite `2.8.6`

Package.json:
```
"@cosmjs/proto-signing": "^0.29.0",
"@cosmology/core": "^1.8.0",
```

Thanks a bunch!

**Comment by aidanaden** [comment]
@pyramation

**Comment by pyramation** [comment]
@aidanaden thanks! checking this out now

**Comment by pyramation** [comment]
I'm not able to reproduce this — can you share (perhaps privately if needed) how to build your app so I can test it? My telegram is the same username as my github too if you want to chat

**Comment by pyramation** [comment]
🙌🏻
