### ISSUE TITLE
How to instantiate these parameters？

### ISSUE THREAD

**Issue by huzi0007** [cosmology-tech/cosmology#18]
links: https://github.com/cosmology-tech/cosmology/tree/main/packages/core#lookuproutesfortrade

How to instantiate the parameters marked in the red box in the picture? Can you give a detailed process? Thank you

![image](https://user-images.githubusercontent.com/37242575/195800852-1c5ba895-5a8f-43f1-a6be-351c09e1c6cc.png)

**Comment by pyramation** [comment]
https://github.com/cosmology-tech/cosmology/issues/17
