### ISSUE TITLE
CoinGecko API response error: AxiosError: connect ETIMEDOUT 162.125.6.1:443

### ISSUE THREAD

**Issue by LIUYX52** [cosmology-tech/cosmology#27]
const rpcEndpoint = "https://rpc.cosmos.directory/osmosis"
  const client = await osmosis.ClientFactory.createRPCQueryClient({ rpcEndpoint });
  
  const {
    pools,
    prices,
    pairs,
    prettyPools
  } = await getPoolsPricesPairs(client);

CoinGecko API response error: AxiosError: connect ETIMEDOUT 162.125.6.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  port: 443,
  address: '162.125.6.1',
  syscall: 'connect',
  code: 'ETIMEDOUT',
  errno: -4039,

Is there something wrong with my network ?

**Comment by pyramation** [comment]
yea this just means there is an issue with the network, or the node took too long. You can catch the error and handle depending on your needs.

thanks!
